runtime: python39
instance_class: F2

env_variables:
  MONGO_URI: "mongodb+srv://username:password@cluster0.mongodb.net/aisyncy_recharge?retryWrites=true&w=majority"
  ADMIN_USERNAME: admin
  ADMIN_PASSWORD: admin123
  WHATSAPP_PHONE_NUMBER_ID: 104612292631543
  WHATSAPP_ACCESS_TOKEN: EAAwFo4oYpGgBO8ZAgKQxZB7dxQY8XnArrLxRsvuhZARG8NJVwQPiJ15EuJq30fV1x4eohl7zT4tHwegGaBcpqtVZADA8QOLKgJwL92etZC7HbZCeujbtr01yxcbFiZBFMUtfPr8RtriO8ZCxXCSWUvMxOynVhmy4ZBHtUzcbTGzLxPUdnIJMeyolNKjcpD376l1WZAJQZDZD
  WHATSAPP_TOKEN: EAAwFo4oYpGgBO8ZAgKQxZB7dxQY8XnArrLxRsvuhZARG8NJVwQPiJ15EuJq30fV1x4eohl7zT4tHwegGaBcpqtVZADA8QOLKgJwL92etZC7HbZCeujbtr01yxcbFiZBFMUtfPr8RtriO8ZCxXCSWUvMxOynVhmy4ZBHtUzcbTGzLxPUdnIJMeyolNKjcpD376l1WZAJQZDZD
  SECRET_KEY: 483e9d3234249efb49ab9383b786a2a7
  WEBHOOK_VERIFY_TOKEN: "12345"
  WHATSAPP_API_URL: "https://graph.facebook.com/v17.0/${WHATSAPP_PHONE_NUMBER_ID}/messages"
  OPENAI_API_KEY: "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"
  OPENAI_MODEL: "gpt-3.5-turbo"

handlers:
- url: /webhook.*
  script: auto
  secure: always
  login: optional

- url: /webhook_test
  script: auto
  secure: always
  login: optional

- url: /static
  static_dir: static
  secure: always

- url: /.*
  script: auto
  secure: always

automatic_scaling:
  min_instances: 1
  max_instances: 5
  min_idle_instances: 1
  max_concurrent_requests: 50

readiness_check:
  path: "/webhook_test"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300 