steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-south1-docker.pkg.dev/$PROJECT_ID/aisyncy-repo/aisyncy-app', '.']
  
  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-south1-docker.pkg.dev/$PROJECT_ID/aisyncy-repo/aisyncy-app']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'aisyncy-service'
    - '--image'
    - 'asia-south1-docker.pkg.dev/$PROJECT_ID/aisyncy-repo/aisyncy-app'
    - '--region'
    - 'asia-south1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--service-account'
    - '1040441775881-compute@developer.gserviceaccount.com'
    - '--update-secrets'
    - 'WHATSAPP_PHONE_NUMBER_ID=WHATSAPP_PHONE_NUMBER_ID:latest,WHATSAPP_TOKEN=WHATSAPP_TOKEN:latest,MONGO_URI=MONGO_URI:latest,FLASK_SECRET_KEY=FLASK_SECRET_KEY:latest'
    - '--set-env-vars'
    - 'WEBHOOK_VERIFY_TOKEN=12345,MONGO_DB=aisyncy_recharge'

images:
  - 'asia-south1-docker.pkg.dev/$PROJECT_ID/aisyncy-repo/aisyncy-app'

options:
  logging: CLOUD_LOGGING_ONLY 